version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: devmatcher-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: devmatcher
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: devmatcher-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
